### ISSUE TITLE
float('inf') in CONFIG file doesn't work in run_favites_docker.py (and potentially Singularity)

### ISSUE THREAD

**Issue by niemasd** [niemasd/FAVITES#27]
```bash
Niemas-Air:Desktop niema$ ~/GitHub/FAVITES/run_favites_docker.py -u -c CONFIG.json
Pulling Docker image (1.1.34)... done
Removing old Docker images... done
Traceback (most recent call last):
  File "/FAVITES/run_favites.py", line 72, in <module>
    parseArgs()
  File "/FAVITES/run_favites.py", line 24, in parseArgs
    config = eval(ORIG_CONFIG)
  File "<string>", line 1, in <module>
NameError: name 'inf' is not defined
```

**Comment by niemasd** [comment]
Fixed in d76f4ca4340ff79775e9bb9ee866d2146c1b5f5a
