### ISSUE TITLE
Does not properly identify seed nodes

### ISSUE THREAD

**Issue by pekarj** [niemasd/FAVITES#34]
## FAVITES Version

1.2.0

## Environment

Docker

## Configuration File

[toy_SAPHIRE.json.zip](https://github.com/niemasd/FAVITES/files/5013262/toy_SAPHIRE.json.zip)

## Unexpected Behavior

I set up 20000 nodes fro the contact network, 1 seed "P" node, and 19999 susceptible "S" nodes, but FAVITES identified the network as having 20000 seed nodes, rather than 1. 

Error message: 

Performing transmission simulations...Traceback (most recent call last):
  File "/FAVITES/run_favites.py", line 75, in <module>
    MF.modules['Driver'].run('/'.join(expanduser(abspath(argv[0])).split('/')[:-1]), ORIG_CONFIG)
  File "/FAVITES/modules/Driver_Default.py", line 160, in run
    t = MF.modules['TransmissionTimeSample'].sample_time()
  File "/FAVITES/modules/TransmissionTimeSample_SAPHIREGEMF.py", line 64, in sample_time
    return TransmissionTimeSample_SAAPPHIIREGEMF.sample_time()
  File "/FAVITES/modules/TransmissionTimeSample_SAAPPHIIREGEMF.py", line 227, in sample_time
    TransmissionTimeSample_SAAPPHIIREGEMF.prep_GEMF()
  File "/FAVITES/modules/TransmissionTimeSample_SAAPPHIIREGEMF.py", line 137, in prep_GEMF
    assert len(start_states['seed']) == len(GC.seed_nodes), "At time 0, P1+P2+I1+I2+A1+A2 = %d, but there are %d seed nodes. Fix saapphiire_freq_* parameters accordingly" % (len(start_states['seed']),len(GC.seed_nodes))
AssertionError: At time 0, P1+P2+I1+I2+A1+A2 = 20000, but there are 1 seed nodes. Fix saapphiire_freq_* parameters accordingly

**Comment by niemasd** [comment]
Ah yes, this was a bug I found earlier but haven't fixed yet. It's interpreting "1" as 100% rather than a count. Can you try putting the proportion as a fraction (i.e., 1/20000) for now? I need to fix this

**Comment by pekarj** [comment]
Ah, okay. That change worked. Thank you!
