### ISSUE TITLE
Sampling times file not found

### ISSUE THREAD

**Issue by pekarj** [niemasd/FAVITES#41]
When using the TimeSample_File module, FAVITES cannot find the sampling times file. 

## FAVITES Version

1.2.9

## Environment

Mac OS Catalina, using Docker

## Configuration File

Config, contact network, transmission network, and sampling times file attached. 
[config_noSeqs_sampleTimes.json.zip](https://github.com/niemasd/FAVITES/files/7928515/config_noSeqs_sampleTimes.json.zip)
[contact_network_file.txt.zip](https://github.com/niemasd/FAVITES/files/7928516/contact_network_file.txt.zip)
[sampling_times.txt.zip](https://github.com/niemasd/FAVITES/files/7928517/sampling_times.txt.zip)
[transmission_network_file.txt.zip](https://github.com/niemasd/FAVITES/files/7928518/transmission_network_file.txt.zip)

## Unexpected Behavior

I expected FAVITES to read in the sampling times file and then use those times, rather than generate its own. FAVITES appears to incorrectly call the sampling times file. If I swap out TimeSample_File with TimeSample_End and NumTimeSample_File with NumTimeSample_Once, everything works perfectly. 

```
Traceback (most recent call last):
  File "/FAVITES/run_favites.py", line 75, in <module>
    MF.modules['Driver'].run('/'.join(expanduser(abspath(argv[0])).split('/')[:-1]), ORIG_CONFIG)
  File "/FAVITES/modules/Driver_Default.py", line 68, in run
    MF.modules[module].init()
  File "/FAVITES/modules/NumTimeSample_File.py", line 22, in init
    GC.sample_times_lines = [i.strip().split() for i in open(expanduser(GC.sample_time_file)) if len(i.strip()) > 0 and i[0] != '#']
FileNotFoundError: [Errno 2] No such file or directory: 'sampling_times.txt'
```

**Comment by niemasd** [comment]
I just pushed a slight update to the `run_favites_docker.py` script; can you try running now and let me know what it outputs?

https://github.com/niemasd/FAVITES/blob/master/run_favites_docker.py

**Comment by pekarj** [comment]
Looks like it works now! Thanks for fixing that. 

```
/---------------------------------------------------------------------\
| FAVITES - FrAmework for VIral Transmission and Evolution Simulation |
|                            Version 1.2.9                            |
|                         Niema Moshiri 2017                          |
\---------------------------------------------------------------------/

========================   Simulation Process  ========================
Loading contact network... done
Creating ContactNetwork object... done
Selecting seed nodes... done
Infecting seed nodes... done
Performing transmission simulations... done
Finalizing transmission simulations... done
Writing true transmission network to file... done
True transmission network was written to: favites_outdir/error_free_files/transmission_network.txt
Sampling patients in time... done
Evolving trees and sequences to end time... done
Pruning sampled trees... done
Converting trees from time to mutation rate... done
Merging true phylogenetic trees with true seed tree (if applicable)... done
Writing true phylogenetic tree(s) to file(s)... done
True phylogenetic trees were written to: favites_outdir/error_free_files/phylogenetic_trees
Finalizing sequence simulations... done
Writing final sequence data to file... done
True sequence data were written to: favites_outdir/error_free_files


=======================   Real Data Artifacts   =======================
Subsampling contact network nodes... done
Simulating sequencing error... done
Error prone sequence data were written to: favites_outdir/error_prone_files


===========================   Information   ===========================
Output Size (bytes): 3217
Execution Time (seconds): 0


============================   Citations   ============================
Hagberg A.A., Schult D.A., Swart P.J. (2008). "Exploring network structure, dynamics, and function using NetworkX". Proceedings of the 7th Python in Science Conference (SciPy2008), 11-15.
Moshiri N. (2020). "TreeSwift: a massively scalable Python package for trees". SoftwareX. 11:100436.
Moshiri N., Ragonnet-Cronin M., Wertheim J.O., Mirarab S. (2018). "FAVITES: simultaneous simulation of transmission networks, phylogenetic trees, and sequences". Bioinformatics. bty921.
Ratmann O., Hodcroft E.B., Pickles M., Cori A., Hall M., Lycett S., Colijn C., Dearlove B., Didelot X., Frost S., Hossain A.S.M.M., Joy J.B., Kendall M., Kuhnert D., Leventhal G.E., Liang R., Plazzotta G., Poon A.F.Y, Rasmussen D.A., Stadler T., Volz E., Weis C., Brown A.J.L., Fraser C. (2016). "Phylogenetic Tools for Generalized HIV-1 Epidemics: Findings from the PANGEA-HIV Methods Comparison". Mol. Biol. Evol. 34(1), 185-203.
```

**Comment by niemasd** [comment]
Very strange! I didn't actually change any of the running code: I just added file exist checks. I wonder if the sample times filename was entered incorrectly when you tried running it last time?

Either way, glad it's working now! 😄
