### ISSUE TITLE
PANGEA doesn't work in Docker image

### ISSUE THREAD

**Issue by niemasd** [niemasd/FAVITES#8]
## Configuration File
`.travis_tests/test_PANGEA.json`

## Unexpected Behavior
```
/---------------------------------------------------------------------\
| FAVITES - FrAmework for VIral Transmission and Evolution Simulation |
|                            Version 1.0.3                            |
|                         Niema Moshiri 2017                          |
\---------------------------------------------------------------------/
========================   Simulation Process  ========================
Loading contact network...Traceback (most recent call last):
  File "/FAVITES/run_favites.py", line 75, in <module>
    MF.modules['Driver'].run('/'.join(expanduser(abspath(argv[0])).split('/')[:-1]), ORIG_CONFIG)
  File "/FAVITES/modules/Driver_Default.py", line 109, in run
    GC.cn_edge_list = MF.modules['ContactNetworkGenerator'].get_edge_list()
  File "/FAVITES/modules/ContactNetworkGenerator_PANGEA.py", line 58, in get_edge_list
    check_output([GC.Rscript_path,PANGEA_command_script], stderr=open(devnull,'w'))
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['Rscript', 'FAVITES_PANGEA_COMMAND.R']' returned non-zero exit status 1
```

**Comment by niemasd** [comment]
Fixed in 1.1.0
